# Generated by Django 6.0 on 2026-01-02 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_log', models.JSONField(blank=True, null=True)),
                ('ai_used', models.BooleanField(default=False)),
                ('ai_provider', models.CharField(blank=True, max_length=20, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testcases.testcase')),
            ],
            options={
                'db_table': 'test_executions',
                'ordering': ['-started_at'],
            },
        ),
    ]
